MVCEventCalendar/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCEventCalendar.Controllers
{
    public class FeedbackController : Controller
    {

        ClassroomAllocationSystemEntities1 entities = new ClassroomAllocationSystemEntities1();
        // GET: Feedback
        Question question = new Question();
        public ActionResult ViewFeedback()
        {
            ViewBag.AllQuestions = new SelectList(entities.Questions.ToList(), "Question1", "Question1");
            var result = entities.Feedbacks.OrderByDescending(e=>e.FeedbackDate);
           // ViewBag.Allfeedback = result;
            return View(result.ToList());
        }
    }
}

MVCEventCalendar/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCEventCalendar.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image

        ClassroomAllocationSystemEntities1 entities = new ClassroomAllocationSystemEntities1();
        Question question = new Question();
        public ActionResult Image()
        {
            ViewBag.AllQuestions = new SelectList(entities.Questions.ToList(), "Question1", "Question1");
            return View();
        }
        [HttpPost]
        public ActionResult Image(ClassRoom classRoom,String Command,string ClassRoomName,int SeatingCapacity,string BuildingName,int LevelNo, HttpPostedFileBase file1)
        {
            try
            {
                if (Command == "Add Details") { 
                if (file1 != null)
                {
                        string fileName = System.IO.Path.GetFileName(file1.FileName);

                        string filePath = "~/Content/Images/ClassroomImages" + fileName;

                        file1.SaveAs(Server.MapPath(filePath));
                        byte[] bytes = null;
                        using (BinaryReader br = new System.IO.BinaryReader(file1.InputStream))
                        {
                            bytes = br.ReadBytes(file1.ContentLength);
                        }
                        using (SqlConnection connection = new SqlConnection("server=VDI-NET-0010\\LOCAL;database=ClassroomAllocationSystem;trusted_connection=true"))
                        {
                            connection.Open();
                            SqlCommand command = new SqlCommand("insert into ClassRooms(ClassRoomName,ClassroomImage,SeatingCapacity,BuildingName,LevelNo) values(@name,@image,@seat,@building,@level)", connection);
                            command.Parameters.AddWithValue("@name", ClassRoomName);
                            command.Parameters.AddWithValue("@image", bytes);
                            command.Parameters.AddWithValue("@seat", SeatingCapacity);
                            command.Parameters.AddWithValue("@building", BuildingName);
                            command.Parameters.AddWithValue("@level", LevelNo);
                            command.ExecuteNonQuery();
                        }
                        return Content("<script languagr='javascript' type='text/javascript'>alert('Classroom register Successfully');window.location = '/Image/Image';</script>");
                        //return Content("<script languagr='javascript' type='text/javascript'>alert('Data added to the database successfully');window.location = '/Image/Image';<script>");
                    }
                }
                return View();
            }
            catch (Exception)
            {

                return Content("<script languagr='javascript' type='text/javascript'>alert('Classroom already register');window.location = '/Image/Image';</script>");
            }
        }
        public ActionResult List()
        {
            ViewBag.AllQuestions = new SelectList(entities.Questions.ToList(), "Question1", "Question1");
            List<ClassRoom> classRooms = GetClasses();
           
            return View(classRooms);
        }
        public ActionResult Delete()
        {
            ViewBag.AllQuestions = new SelectList(entities.Questions.ToList(), "Question1", "Question1");
            return PartialView("_DeleteClassroom", entities.ClassRooms);
        }

        private List<ClassRoom> GetClasses()
        {
            List<ClassRoom> images = new List<ClassRoom>();
            SqlConnection connection = new SqlConnection("server=VDI-NET-0010\\LOCAL;database=ClassroomAllocationSystem;trusted_connection=true");
            connection.Open();
            SqlCommand command = new SqlCommand("Select * from ClassRooms", connection);
            using (SqlDataReader sdr = command.ExecuteReader())
            {
                while (sdr.Read())
                {
                    images.Add(new ClassRoom
                    {
                       
                        ClassRoomName = sdr["ClassRoomName"].ToString(),
                        
                        ClassroomImage = (byte[])sdr["ClassroomImage"],
 
                    }

                    );
                    
                }
            }
            connection.Close();
            return images;
        }
        //public ActionResult Delete()
        //{
        //    return View();
        //}

    }
}

MVCEventCalendar/Views/Resource/AddResources.cshtml
@model MVCEventCalendar.Resource

@{
    ViewBag.Title = "AddResources";
}

<h2>AddResources</h2>


@using (Html.BeginForm("AddResources", "Resource",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Resource</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.ResourceId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResourceId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResourceId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ResourceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResourceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResourceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Resources" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "Welcome")
</div>

MVCEventCalendar/Views/Resource/Welcome.cshtml
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
@{
    ViewBag.Title = "Welcome";
}

<style>
    * {
        margin: 0px;
        padding: 0px;
        font-family: 'Times New Roman';
    }

    #sidenav {
        height: 100%;
        width: 260px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: black;
        color: white;
        overflow-x: hidden;
        padding-top: 20px;
        padding-left: 5px;
        margin-top: 50px;
    }

        #sidenav a {
            /*padding:6px, 8px,6px,16px;*/
            text-decoration: none;
            font-size: 20px;
            color: #818181;
            display: block;
            padding: 12px;
        }

            #sidenav a:hover {
                color: #f1f1f1;
            }

    .body1 {
        margin-left: 260px;
        font-size: 10px;
        padding: 0px,10px;
    }

    /*#sidenav ul li {
      list-style:none;
    }*/
   section ul li{
        list-style:none;
    }
</style>
<body>
    <section class="col-md-1" id="sidenav">
        <ul>
            <li>
                @Ajax.ActionLink("Add Resources", "AddResources", new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "div1"
                })
            </li>
            <li>
                @Ajax.ActionLink("Delete Resource", "DeleteResource", new AjaxOptions
           {
               HttpMethod="GET",
               InsertionMode=InsertionMode.Replace,
               UpdateTargetId="div1"
           })
            </li>

            <li>
                @Ajax.ActionLink("Add Classroom", "Image", "Image", new AjaxOptions {
               HttpMethod="GET",
               InsertionMode=InsertionMode.Replace,
               UpdateTargetId="div1"
           })
            </li>
            <li>
                @Ajax.ActionLink("List of all Classroom", "List", "Image", new AjaxOptions {
               HttpMethod="GET",
               InsertionMode=InsertionMode.Replace,
               UpdateTargetId="div1"
           })
            </li>
            <li>
                @Ajax.ActionLink("Delete Classroom", "DeleteClassroom", "Image", new AjaxOptions {
               HttpMethod="GET",
               InsertionMode=InsertionMode.Replace,
               UpdateTargetId="div1"
           })
            </li>
            <li>
                @Ajax.ActionLink("Update Classroom","UpadateClassroom", "Image", new AjaxOptions {
               HttpMethod="GET",
               InsertionMode=InsertionMode.Replace,
               UpdateTargetId="div1"
           })
            </li>

            <li>
                @Ajax.ActionLink("Add Classroom Details", "AddClassroomDetails","ClassroomDetails",new AjaxOptions {
                HttpMethod="GET",
                InsertionMode=InsertionMode.Replace,
                UpdateTargetId="div1"
            })
            </li>
            <li>
                @Ajax.ActionLink("Delete Classroom Details", "DeleteClassroomDetails", "ClassroomDetails",new AjaxOptions {
               HttpMethod="GET",
               InsertionMode=InsertionMode.Replace,
               UpdateTargetId="div1"
           })
            </li>
            @*<li>
                     @Ajax.ActionLink("Update Classroom Details", "UpdateClassroomDetails", "ClassroomDetails",new AjaxOptions {
                    HttpMethod="GET",
                    InsertionMode=InsertionMode.Replace,
                    UpdateTargetId="div1"
                })
                 </li>*@
            <li>
                @Ajax.ActionLink("View Feedback", "Index", "Feedback",new AjaxOptions {
               HttpMethod="GET",
               InsertionMode=InsertionMode.Replace,
               UpdateTargetId="div1"
           })
            </li>
        </ul>
    </section>

    <div id="div1"></div>

</body>